// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  room: __t.string(),
  name: __t.string(),
  color: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  rot: __t.f32(),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

