// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  creatorPlayerId: __t.string().name("creator_player_id"),
  title: __t.string(),
  description: __t.string(),
  buildingId: __t.string().name("building_id"),
  get position() {
    return Vec3;
  },
  startTime: __t.timestamp().name("start_time"),
  endTime: __t.option(__t.timestamp()).name("end_time"),
  tags: __t.array(__t.string()),
});
