// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomId: __t.string().name("room_id"),
  campus: __t.string(),
  buildingId: __t.string().name("building_id"),
  activeQuestCount: __t.u32().name("active_quest_count"),
  completedQuestCount: __t.u32().name("completed_quest_count"),
  categoryCountsJson: __t.string().name("category_counts_json"),
  conceptTagCountsJson: __t.string().name("concept_tag_counts_json"),
  updatedAt: __t.timestamp().name("updated_at"),
});
