// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  buildingId: __t.string().name("building_id"),
  title: __t.string(),
  description: __t.string(),
  category: __t.string(),
  replitTemplateUrl: __t.string().name("replit_template_url"),
  estimatedMinutes: __t.u32().name("estimated_minutes"),
  skills: __t.array(__t.string()),
});
