// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  playerId: __t.string().name("player_id"),
  portalId: __t.string().name("portal_id"),
  status: __t.string(),
  startedAt: __t.option(__t.timestamp()).name("started_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  lastStatusCheckAt: __t.option(__t.timestamp()).name("last_status_check_at"),
});
