// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec3,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.identity(),
  roomId: __t.string().name("room_id"),
  displayName: __t.string().name("display_name"),
  avatarColor: __t.string().name("avatar_color"),
  get position() {
    return Vec3;
  },
  rotationY: __t.f32().name("rotation_y"),
  activeQuestId: __t.option(__t.string()).name("active_quest_id"),
  connected: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
});
