// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Buildings = __t.object("Buildings", {
  id: __t.string(),
  name: __t.string(),
  get position() {
    return Vec3;
  },
  campus: __t.string(),
});
export type Buildings = __Infer<typeof Buildings>;

export const EventRsvps = __t.object("EventRsvps", {
  id: __t.string(),
  eventId: __t.string(),
  playerId: __t.string(),
  status: __t.string(),
});
export type EventRsvps = __Infer<typeof EventRsvps>;

export const Events = __t.object("Events", {
  id: __t.string(),
  roomId: __t.string(),
  creatorPlayerId: __t.string(),
  title: __t.string(),
  description: __t.string(),
  buildingId: __t.string(),
  get position() {
    return Vec3;
  },
  startTime: __t.timestamp(),
  endTime: __t.option(__t.timestamp()),
  tags: __t.array(__t.string()),
});
export type Events = __Infer<typeof Events>;

export const LearningPortals = __t.object("LearningPortals", {
  id: __t.string(),
  buildingId: __t.string(),
  title: __t.string(),
  description: __t.string(),
  category: __t.string(),
  replitTemplateUrl: __t.string(),
  estimatedMinutes: __t.u32(),
  skills: __t.array(__t.string()),
});
export type LearningPortals = __Infer<typeof LearningPortals>;

export const LearningStats = __t.object("LearningStats", {
  id: __t.string(),
  roomId: __t.string(),
  campus: __t.string(),
  buildingId: __t.string(),
  activeQuestCount: __t.u32(),
  completedQuestCount: __t.u32(),
  categoryCountsJson: __t.string(),
  conceptTagCountsJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LearningStats = __Infer<typeof LearningStats>;

export const PlayerQuests = __t.object("PlayerQuests", {
  id: __t.string(),
  playerId: __t.string(),
  portalId: __t.string(),
  status: __t.string(),
  startedAt: __t.option(__t.timestamp()),
  completedAt: __t.option(__t.timestamp()),
  lastStatusCheckAt: __t.option(__t.timestamp()),
});
export type PlayerQuests = __Infer<typeof PlayerQuests>;

export const Players = __t.object("Players", {
  id: __t.string(),
  owner: __t.identity(),
  roomId: __t.string(),
  displayName: __t.string(),
  avatarColor: __t.string(),
  get position() {
    return Vec3;
  },
  rotationY: __t.f32(),
  activeQuestId: __t.option(__t.string()),
  connected: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Players = __Infer<typeof Players>;

export const Rooms = __t.object("Rooms", {
  id: __t.string(),
  name: __t.string(),
  code: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Rooms = __Infer<typeof Rooms>;

export const Vec3 = __t.object("Vec3", {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type Vec3 = __Infer<typeof Vec3>;

