// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import EnterGameReducer from "../enter_game_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import UpdateTransformReducer from "../update_transform_reducer";

export type EnterGameParams = __Infer<typeof EnterGameReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type UpdateTransformParams = __Infer<typeof UpdateTransformReducer>;

