import type { Building, CampusEvent, LearningPortal } from "./types";

export const DEMO_ROOM = {
  id: "room-demo",
  name: "FordhamVerse Demo",
  code: "RAMS",
  status: "live",
};

export const AVATAR_COLORS = [
  "#22c55e",
  "#38bdf8",
  "#f97316",
  "#a78bfa",
  "#f43f5e",
  "#facc15",
];

// ─── Fordham University — Rose Hill Campus ──────────────────────────────────────
// Layout mirrors the real Rose Hill geography: Edwards Parade is the central lawn,
// Keating Hall sits on its east edge, Dealy Hall to the west, with the gothic
// University Church and Collins Auditorium to the north. (x: east+, z: south+)
export const BUILDINGS: Building[] = [
  {
    id: "b-keating",
    name: "Keating Hall",
    shortName: "Keating — Administration",
    position: { x: 10, y: 0, z: -1 },
    size: [5, 9, 4],
    campus: "rose_hill",
    color: "#3a3340",
    landmark: "tower",
  },
  {
    id: "b-church",
    name: "University Church",
    shortName: "University Church",
    position: { x: -11, y: 0, z: -10 },
    size: [3.5, 7, 6],
    campus: "rose_hill",
    color: "#2f2a38",
    landmark: "spire",
  },
  {
    id: "b-collins",
    name: "Collins Auditorium",
    shortName: "Collins — Events",
    position: { x: -6, y: 0, z: -10 },
    size: [5, 4, 4],
    campus: "rose_hill",
    color: "#2a2418",
  },
  {
    id: "b-hughes",
    name: "Hughes Hall",
    shortName: "Hughes — Gabelli Business",
    position: { x: 1, y: 0, z: -11 },
    size: [5, 5, 3],
    campus: "rose_hill",
    color: "#1f2a1a",
  },
  {
    id: "b-duane",
    name: "Duane Library",
    shortName: "Duane Library",
    position: { x: -4, y: 0, z: -6 },
    size: [4, 4, 3],
    campus: "rose_hill",
    color: "#1a1f2e",
  },
  {
    id: "b-dealy",
    name: "Dealy Hall",
    shortName: "Dealy — Humanities",
    position: { x: -11, y: 0, z: 0 },
    size: [3, 5, 7],
    campus: "rose_hill",
    color: "#2a2f3d",
  },
  {
    id: "b-mcshane",
    name: "McShane Campus Center",
    shortName: "McShane — Student Hub",
    position: { x: 14, y: 0, z: -6 },
    size: [5, 4, 4],
    campus: "rose_hill",
    color: "#1a2420",
  },
  {
    id: "b-walsh-lib",
    name: "Walsh Family Library",
    shortName: "Walsh Library",
    position: { x: 5, y: 0, z: 11 },
    size: [7, 5, 4],
    campus: "rose_hill",
    color: "#1a2438",
  },
  {
    id: "b-freeman",
    name: "Freeman Hall",
    shortName: "Freeman — Science",
    position: { x: -6, y: 0, z: 10 },
    size: [5, 4, 3],
    campus: "rose_hill",
    color: "#243038",
  },
  {
    id: "b-jmh",
    name: "John Mulcahy Hall",
    shortName: "JMH — Science Labs",
    position: { x: 11, y: 0, z: 10 },
    size: [5, 5, 3],
    campus: "rose_hill",
    color: "#1f2630",
  },
  {
    id: "b-ohare",
    name: "O'Hare Hall",
    shortName: "O'Hare — Residence",
    position: { x: 16, y: 0, z: 3 },
    size: [3, 6, 4],
    campus: "rose_hill",
    color: "#241f2a",
  },
  {
    id: "b-martyrs",
    name: "Martyrs' Court",
    shortName: "Martyrs' Court — Residence",
    position: { x: -15, y: 0, z: -6 },
    size: [4, 4, 6],
    campus: "rose_hill",
    color: "#1f241f",
  },
];

export const PORTALS: LearningPortal[] = [
  {
    id: "p-freeman-ml",
    buildingId: "b-freeman",
    position: { x: -6, z: 7.2 },
    title: "Intro to Machine Learning",
    description:
      "Build your first neural network in Freeman Hall's science labs to predict student outcomes from real data.",
    category: "ml",
    replitTemplateUrl: "https://replit.com/@replit/Python",
    estimatedMinutes: 45,
    skills: ["Python", "scikit-learn", "Pandas"],
    difficulty: "Intermediate",
  },
  {
    id: "p-walsh-data",
    buildingId: "b-walsh-lib",
    position: { x: 4.5, z: 7.8 },
    title: "Data Structures 101",
    description:
      "Deep in the Walsh Library stacks, master linked lists, trees, and the algorithms that power search.",
    category: "data",
    replitTemplateUrl: "https://replit.com/@replit/Java",
    estimatedMinutes: 30,
    skills: ["Java", "Algorithms"],
    difficulty: "Starter",
  },
  {
    id: "p-hughes-startup",
    buildingId: "b-hughes",
    position: { x: 1, z: -8.5 },
    title: "Build a Startup MVP",
    description:
      "At the Gabelli School in Hughes Hall, ship a landing page and pitch your startup idea to the Verse.",
    category: "startup",
    replitTemplateUrl: "https://replit.com/@replit/React-TypeScript",
    estimatedMinutes: 60,
    skills: ["React", "CSS", "Marketing"],
    difficulty: "Intermediate",
  },
  {
    id: "p-mcshane-front",
    buildingId: "b-mcshane",
    position: { x: 10.5, z: -6 },
    title: "Frontend Masterclass",
    description:
      "In the McShane Campus Center, design a beautiful, responsive UI with modern Tailwind CSS.",
    category: "frontend",
    replitTemplateUrl: "https://replit.com/@replit/HTML-CSS-JS",
    estimatedMinutes: 25,
    skills: ["HTML", "CSS", "Tailwind"],
    difficulty: "Starter",
  },
  {
    id: "p-collins-infra",
    buildingId: "b-collins",
    position: { x: -7, z: -6.8 },
    title: "Deploying to the Cloud",
    description:
      "On the Collins Auditorium stage, take an Express server from localhost to a live deployment.",
    category: "infra",
    replitTemplateUrl: "https://replit.com/@replit/Nodejs",
    estimatedMinutes: 50,
    skills: ["Node.js", "Deployment"],
    difficulty: "Advanced",
  },
  {
    id: "p-keating-general",
    buildingId: "b-keating",
    position: { x: 6.5, z: -1 },
    title: "Code Your First App",
    description:
      "Beneath Keating Hall's iconic clock tower, write your very first program and run it instantly.",
    category: "general",
    replitTemplateUrl: "https://replit.com/@replit/Python",
    estimatedMinutes: 20,
    skills: ["Programming", "Logic"],
    difficulty: "Starter",
  },
];

export const EVENTS: CampusEvent[] = [
  {
    id: "evt-1",
    roomId: DEMO_ROOM.id,
    creatorPlayerId: "system",
    title: "Hackathon Kickoff",
    description:
      "Gather on the north lawn by Collins Auditorium to kick off the annual Fordham Hackathon. Teams, prizes, and pizza!",
    buildingId: "b-collins",
    position: { x: -4, y: 0, z: -2 },
    startTime: Date.now() + 3600000,
    endTime: Date.now() + 7200000,
    tags: ["Hackathon", "Coding", "Social"],
  },
  {
    id: "evt-2",
    roomId: DEMO_ROOM.id,
    creatorPlayerId: "system",
    title: "AI Study Group",
    description: "Study group for CS401 Machine Learning, meeting outside Freeman Hall.",
    buildingId: "b-freeman",
    position: { x: -5, y: 0, z: 7 },
    startTime: Date.now() + 86400000,
    endTime: null,
    tags: ["AI", "Study", "Freeman"],
  },
  {
    id: "evt-3",
    roomId: DEMO_ROOM.id,
    creatorPlayerId: "system",
    title: "Spring Concert on the Parade",
    description:
      "Live music and food trucks on Edwards Parade, the heart of the Rose Hill campus.",
    buildingId: "b-keating",
    position: { x: 3, y: 0, z: 3 },
    startTime: Date.now() + 172800000,
    endTime: null,
    tags: ["Music", "Festival", "Edwards Parade"],
  },
];
