import { Building, CampusEvent, LearningPortal } from "./types";

export const DEMO_ROOM = {
  id: "room-demo",
  name: "FordhamVerse Demo",
  code: "RAMS",
  status: "live",
};

export const AVATAR_COLORS = [
  "#22c55e",
  "#38bdf8",
  "#f97316",
  "#a78bfa",
  "#f43f5e",
  "#facc15",
];

export const BUILDINGS: Building[] = [
  {
    id: "b-freeman",
    name: "Freeman Hall",
    shortName: "CS & Engineering",
    position: { x: -8, y: 0, z: -6 },
    size: [4, 5, 3],
    campus: "rose_hill",
    color: "#1a2744",
  },
  {
    id: "b-duane",
    name: "Duane Library",
    shortName: "Library",
    position: { x: 0, y: 0, z: -8 },
    size: [6, 4, 3],
    campus: "rose_hill",
    color: "#1a1f2e",
  },
  {
    id: "b-keating",
    name: "Keating Hall",
    shortName: "Admin",
    position: { x: 8, y: 0, z: -5 },
    size: [5, 7, 4],
    campus: "rose_hill",
    color: "#2a1f3d",
  },
  {
    id: "b-gabelli",
    name: "Gabelli School",
    shortName: "Business",
    position: { x: -7, y: 0, z: 5 },
    size: [5, 4, 3],
    campus: "rose_hill",
    color: "#1f2a1a",
  },
  {
    id: "b-alumni",
    name: "Alumni House",
    shortName: "Social Hub",
    position: { x: 7, y: 0, z: 4 },
    size: [4, 3, 3],
    campus: "rose_hill",
    color: "#1a2420",
  },
  {
    id: "b-collins",
    name: "Collins Auditorium",
    shortName: "Events",
    position: { x: 0, y: 0, z: 5 },
    size: [6, 3, 4],
    campus: "rose_hill",
    color: "#2a2015",
  },
];

export const PORTALS: LearningPortal[] = [
  {
    id: "p-freeman-ml",
    buildingId: "b-freeman",
    title: "Intro to Machine Learning",
    description: "Build your first neural network to predict student grades.",
    category: "ml",
    replitTemplateUrl: "https://replit.com/@replit/Python",
    estimatedMinutes: 45,
    skills: ["Python", "scikit-learn", "Pandas"],
    difficulty: "Intermediate",
  },
  {
    id: "p-duane-data",
    buildingId: "b-duane",
    title: "Data Structures 101",
    description: "Learn how to use linked lists and trees.",
    category: "data",
    replitTemplateUrl: "https://replit.com/@replit/Java",
    estimatedMinutes: 30,
    skills: ["Java", "Algorithms"],
    difficulty: "Starter",
  },
  {
    id: "p-gabelli-startup",
    buildingId: "b-gabelli",
    title: "Build a Startup MVP",
    description: "Create a simple landing page for your startup idea.",
    category: "startup",
    replitTemplateUrl: "https://replit.com/@replit/React-TypeScript",
    estimatedMinutes: 60,
    skills: ["React", "CSS", "Marketing"],
    difficulty: "Intermediate",
  },
  {
    id: "p-alumni-front",
    buildingId: "b-alumni",
    title: "Frontend Masterclass",
    description: "Style a beautiful UI with Tailwind CSS.",
    category: "frontend",
    replitTemplateUrl: "https://replit.com/@replit/HTML-CSS-JS",
    estimatedMinutes: 25,
    skills: ["HTML", "CSS"],
    difficulty: "Starter",
  },
  {
    id: "p-collins-infra",
    buildingId: "b-collins",
    title: "Deploying to the Cloud",
    description: "Take an Express server and deploy it live.",
    category: "infra",
    replitTemplateUrl: "https://replit.com/@replit/Nodejs",
    estimatedMinutes: 50,
    skills: ["Node.js", "Docker"],
    difficulty: "Advanced",
  },
];

export const EVENTS: CampusEvent[] = [
  {
    id: "evt-1",
    roomId: DEMO_ROOM.id,
    creatorPlayerId: "system",
    title: "Hackathon Kickoff",
    description: "Join us at Collins Auditorium to kick off the annual Fordham Hackathon!",
    buildingId: "b-collins",
    position: { x: -2, y: 0, z: 2 },
    startTime: Date.now() + 3600000,
    endTime: Date.now() + 7200000,
    tags: ["Hackathon", "Coding", "Social"],
  },
  {
    id: "evt-2",
    roomId: DEMO_ROOM.id,
    creatorPlayerId: "system",
    title: "AI Study Group",
    description: "Study group for CS401 Machine Learning.",
    buildingId: "b-freeman",
    position: { x: -6, y: 0, z: -3 },
    startTime: Date.now() + 86400000,
    endTime: null,
    tags: ["AI", "Study", "Freeman"],
  },
];
