// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteQuestReducer from "../complete_quest_reducer";
import CreateEventReducer from "../create_event_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LaunchPortalReducer from "../launch_portal_reducer";
import RecordConceptTagsReducer from "../record_concept_tags_reducer";
import RsvpEventReducer from "../rsvp_event_reducer";
import SetRoomStatusReducer from "../set_room_status_reducer";
import UpdateConnectionReducer from "../update_connection_reducer";
import UpdatePlayerPoseReducer from "../update_player_pose_reducer";

export type CompleteQuestParams = __Infer<typeof CompleteQuestReducer>;
export type CreateEventParams = __Infer<typeof CreateEventReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LaunchPortalParams = __Infer<typeof LaunchPortalReducer>;
export type RecordConceptTagsParams = __Infer<typeof RecordConceptTagsReducer>;
export type RsvpEventParams = __Infer<typeof RsvpEventReducer>;
export type SetRoomStatusParams = __Infer<typeof SetRoomStatusReducer>;
export type UpdateConnectionParams = __Infer<typeof UpdateConnectionReducer>;
export type UpdatePlayerPoseParams = __Infer<typeof UpdatePlayerPoseReducer>;

